### ISSUE TITLE
Diffing: RPC PermissionDenied 

### ISSUE THREAD

**Issue by mar-ki** [zapier/kubechecks#191]
Using a docker image **>= v1.5.3** I get following issue during the argo diff operation

```
10:28AM INF check result error="rpc error: code = PermissionDenied desc = permission denied" app=myapp app_name=myapp app_path=application/myapp/manifests check="generating diff for app" event_id=59 repo=kubechecks-test result=
```

The token used to connect to my argocd installation has admin permissions and the debug log doesn't provide any more info on that topic.

PS: Images older than v1.5.3 can run the diff but always detect "created" instead of "modified". For example when changing replica counts in plain manifests.

**Comment by djeebus** [comment]
Interesting! The "permission denied" should be resolved with #187 , and will be released shortly. 

The second issue (modifications look like creations) is strange. does the "myapp" app exist in argocd already, and is functional? if it's in git but not yet in the cluster, that would explain why kubechecks thinks you're creating the resources. otherwise there's something else we need to track down here. anything interesting going on with that app?

**Comment by mar-ki** [comment]
Hey djeebus, thanks for that feedback. Looking forward to use that feature in the future. 

About the second issue

The app(s) are already deployed and up & running within my cluster.

**Example**

I have an app-of-projects that is managing my argocd projects. It uses a simple helm chart that templates AppProjects based on some values. 

If I add a new project and create the merge request kubechecks will detect everything as "added", even those projects that are already live. This results in a pretty large output.

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-projects
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: master
  source:
    path: 'bootstrap/app-of-projects'
    repoURL: "https://xyz.net/argo-bootstrap.git"
    targetRevision: HEAD
    helm:
      releaseName: "projects"
  syncPolicy:
    automated:
      selfHeal: true
```

**Comment by mar-ki** [comment]
I identified the root cause. We use the "Applications in any namespace" feature. A team could deploy an Argo Application in their namespace and then it get synced to argo and deployed. 
Documentation: [app-any-namespace](https://argo-cd.readthedocs.io/en/stable/operator-manual/app-any-namespace/ )

This causes Kubechecks to always say that any modifications are "added" even when something is modified or deleted.

I started to move the applications into the argocd namespace and it's running fine now

**Example - Not working (App Manifest in team ns)**
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app3-manifests
  namespace: app3
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: app3
    server: https://kubernetes.default.svc
  project: team-apps
  source:
    repoURL: https://xyz.net/argo-bootstrap.git
    path: application/app3-manifest/manifests
  syncPolicy:
    automated:
      selfHeal: true
```
**Example - Working (Application manifest in argocd ns)**
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app3-manifests
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: app3
    server: https://kubernetes.default.svc
  project: team-apps
  source:
    repoURL: https://xyz.net/argo-bootstrap.git
    path: application/app3-manifest/manifests
  syncPolicy:
    automated:
      selfHeal: true
```
