### ISSUE TITLE
New applicationset diff only shows the last cluster when multiple generators specified

### ISSUE THREAD

**Issue by audrey-mux** [zapier/kubechecks#270]
Hi

Upgraded to to 1.70 recently to get the new appset generation capability (thanks for that btw, super useful), but wondering if there might be a bug. I have this generator: 
```yaml
  generators:
    - clusters:
        selector:
          matchLabels:
            environment: staging
            provider: oci
        values:
          environment: staging
          version: "0.0.1"
    - clusters:
        selector:
          matchLabels:
            environment: production
            provider: oci
        values:
          environment: production
          version: "0.0.1"
```

Currently, each generator will match a single cluster so i would expect to see output for both the staging and production cluster. However, only the production cluster shows up in the `Kubechecks Report` output.  

The first generator does actually match a cluster since it generates a new app for it after the PR is merged.
