### ISSUE TITLE
Add support for multiple ArgoCD servers.

### ISSUE THREAD

**Issue by sl1pm4t** [zapier/kubechecks#29]
Some folks deploy an ArgoCD server per Kubernetes cluster. We should add support for multiple ArgoCD deploys that is configurable:
* per repository
* per application

**Comment by Oded-B** [comment]
Hi, I'm the author of https://github.com/wayfair-incubator/telefonistka, I used this configuration format to support forwarding webhook to arbitrary number of ArgoCDs:
I think a similar configuration could be used.
```
webhookEndpointRegexs:
  - expression: "^workspace/[^/]*/.*"
    replacements:
      - "https://kube-argocd-c1.service.lab.example.com/api/webhoook"
      - "https://kube-argocd-applicationset-c1.service.lab.example.com/api/webhoook"
      - "https://example.com"
  - expression: "^clusters/([^/]*)/([^/]*)/([^/]*)/.*"
    replacements:
      - "https://kube-argocd-${3}.${1}.service.{2}.example.com/api/webhoook"
      - "https://kube-argocd-applicationset-${2}.service.${1}.example.com/api/webhoook"
```

For authentication,  I would k8s Dex oidc connector on server side and have Kubechecks use https://github.com/dexidp/dex/pull/2806 to replace the k8s SA JWT with a valid access token.


BTW I'm half way in implementing "post argocd diff in PR comment" in Telefonistka and just ran in to your amazing project.
I'm considering just using kubechecks, but I'm not sure it will be fully compatible to my future plans
