### ISSUE TITLE
Diff for applications with multiple sources

### ISSUE THREAD

**Issue by andridzi** [zapier/kubechecks#294]
Hello,

It would be greatly appreciated to have this feature, as the current implementation doesn't seem to work for applications with multiple sources (like Helm deployments, where one source is for the Helm chart itself and another for the values).

I noticed an initial effort from @sl1pm4t in #240, but it appears to still be in draft.

**Comment by memdealer** [comment]
YES PLEASE.

**Comment by alaa-404** [comment]
would be gr8 💯

**Comment by djeebus** [comment]
For some reason I remember this working, but that doesn't seem to be true. OK, I built on the work that @sl1pm4t did and got a working branch. I don't have any multi source applications to test on yet, but if anyone wants a sneak preview, you can use the image at `ghcr.io/zapier/kubechecks:0.0.0-pr298`, and report back if it works as intended.

**Comment by andridzi** [comment]
@djeebus, I'll test and comment

**Comment by andridzi** [comment]
@djeebus, so, it's not crashing anymore but still not working
current setup

```
    sources:
      - repoURL: https://charts.fairwinds.com/stable
        chart: rbac-manager
        targetRevision: 1.6.0
        helm:
          releaseName: rbac-manager
          valueFiles:
          - '$values/{{metadata.labels.environment}}/rbac-manager/{{name}}.yaml'
      - repoURL: https://github.com/andridzi/helm-values.git
        targetRevision: master
        ref: values
```
first error - it failed to clone `https://stakater.github.io/stakater-charts` repo
```
3:56PM ERR Unable to clone repository error="failed to clone repo: failed to clone repository: exit status 128" app_name=rbac-manager app_path= event_id=476 repo=argocd workerID=0
3:56PM INF cloning git repo branch=1.6.0 clone-url=https://andridzi@charts.fairwinds.com/stable temp-dir=/tmp/kubechecks-repo-1262552353
```

after changing git ref to 
```
      sources:
        repoURL: git@github.com:FairwindsOps/charts.git
        path: stable/rbac-manager
```

it failed with error that it couldn't find the values file
