### ISSUE TITLE
Panic on multi-source apps v1.8.0

### ISSUE THREAD

**Issue by audrey-mux** [zapier/kubechecks#297]
Ran across a panic when trying to process a multi-source app. We just started using those and this is the second one so far, the first one just produced a warning w/o the panic

```shell
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x2565b90]

goroutine 850 [running]:
github.com/zapier/kubechecks/pkg/events.(*worker).processApp(_, {_, _}, {{{0x398691d, 0xb}, {0x39a788d, 0x14}}, {{0xc004596dc8, 0x18}, {0x0, ...}, ...}, ...})
	github.com/zapier/kubechecks//pkg/events/worker.go:59 +0x90
github.com/zapier/kubechecks/pkg/events.(*worker).run(0xc002943808, {0x43c93d8, 0xc004761830})
	github.com/zapier/kubechecks/pkg/events/worker.go:39 +0x170
created by github.com/zapier/kubechecks/pkg/events.(*CheckEvent).Process in goroutine 785
	github.com/zapier/kubechecks/pkg/events/check.go:284 +0x5d5
```

**Comment by djeebus** [comment]
Looks like there are some core chunks of the app that are not aware of multiple sources. Might not be too difficult to take into account. 🤞

**Comment by audrey-mux** [comment]
i'll give it a shot

**Comment by audrey-mux** [comment]
I tried that build out in my test instance with a new multi-source app - no crash, but i'm seeing permissions errors ( even with a rollback to 1.8.0 ), so i think i can tentatively say its working. but i want to figure out this permission issue before i'd say `totally fixed`

**Comment by audrey-mux** [comment]
Permission issue fixed 

given that this is multi-source the helm chart itself is pulling from a remote repo (generally, we've pull them into our monorepo and haven't had an issue), it looks like Kubechecks isn't able to pull this from this remote helm repo

![Screenshot 2024-10-23 at 10 28 34](https://github.com/user-attachments/assets/1497220e-860e-46d9-b889-1321c53a80a7)

```shell
5:19PM INF cloning repo branchName=1.4.3 event_id=50 repo=repo-name-redacted
5:19PM INF cloning git repo branch=1.4.3 clone-url=https://audrey-mux@grafana.github.io/helm-charts temp-dir=/tmp/kubechecks-repo-489429976
5:19PM DBG building command args=["clone","https://audrey-mux@grafana.github.io/helm-charts","/tmp/kubechecks-repo-489429976","--branch","1.4.3"]
5:19PM DBG getting cluster clusterName= clusterServer=https://kubernetes.default.svc
5:19PM DBG generating diff for application... name=cluster-bootstrap-apps
5:19PM DBG for appname cluster-bootstrap-apps, server dest says: https://kubernetes.default.svc and name dest says: 
5:19PM ERR unable to clone repository, Cloning into '/tmp/kubechecks-repo-489429976'...
fatal: repository 'https://grafana.github.io/helm-charts/' not found
 error="exit status 128"
5:19PM ERR Unable to clone repository error="failed to clone repo: failed to clone repository: exit status 128" app_name=<redacted>-beyla app_path= event_id=50 repo=repo-name-redacted workerID=15
```
and the appset `sources` block:
```yaml
      sources:
        - helm:
            releaseName: beyla
            valueFiles:
              - $values/monitoring/grafana-cloud/beyla/values.yaml
          repoURL: https://grafana.github.io/helm-charts
          chart: beyla
          targetRevision: 1.4.3
        - repoURL: https://github.com/org/repo.git
          targetRevision: master
          ref: values
```
it looks like it think this is a git repo vs a helm repo

**Comment by audrey-mux** [comment]
I also tried moving the chart to a git repo instead with a different outcome

```yaml
      sources:
        - repoURL: https://github.com/org/helmchart.git
          path: tools/helm/beyla
          targetRevision: main
          helm:
            releaseName: beyla
            valueFiles:
            - $values/monitoring/grafana-cloud/beyla/values.yaml
        - repoURL: https://github.com/org/valuesfile.git
          targetRevision: master
          ref: values
```

I had to drop the values file in the helmchart repo otherwise kubechecks couldn't find it -

from what it looks like in the logs, the first repo (helmchart) is checked out and diffed, and then the second repo (valuesfile) is checked out but fails to get the helm chart since it doesn't exist at that path.
