### ISSUE TITLE
Local helm dependency build fails

### ISSUE THREAD

**Issue by FlorisFeddema** [zapier/kubechecks#374]
After I added a new dependency to my helm charts the kubechecks github check fails. 

I added the following dependency and it works in ArgoCD:

```
dependencies:
  - name: gatus-monitor
    repository: file://../../../templates/gatus-monitor
    version: 1.0.0
```

It results in the following error: 
```failed to generate manifests: failed to get response: rpc error: code = Unknown desc = failed to build helm dependencies: failed to build dependencies: failed to get command args to log: `helm dependency build` failed exit status 1: Error: directory ../../../templates/gatus-monitor not found```

However the dependency is working in ArgoCD correctly, thus it looks like kubechecks can not get the path to the correct directory?
