### ISSUE TITLE
support for external helm charts?

### ISSUE THREAD

**Issue by melanger** [zapier/kubechecks#379]
Hi,

I really like this project, but I am not able to get it working. I am trying to run a local K8s cluster with ArgoCD and Kubechecks, connected to a self-hosted GitLab instance. Kubechecks is able to receive the webhook and comment on the MR, but it never finds the applications.

Are applications which just reference external helm charts supported? E.g.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bitnami-nginx
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 15.0.0
    chart: nginx
  destination:
    server: https://kubernetes.default.svc
    namespace: whatever
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
```

Also, do I have to have a specific folder structure or naming of the application manifests files?

I am using this config

```yaml
configMap:
  create: true
  env:
    KUBECHECKS_MONITOR_ALL_APPLICATIONS: "true"
    KUBECHECKS_ARGOCD_API_NAMESPACE: "argocd"
    KUBECHECKS_ADDITIONAL_APPS_NAMESPACES: "*"
    KUBECHECKS_ENABLE_CONFTEST: "true"
    KUBECHECKS_LOG_LEVEL: "trace"
    KUBECHECKS_SHOW_DEBUG_INFO: "true"
    KUBECHECKS_VCS_BASE_URL: "https://gitlab.example.com"
    KUBECHECKS_VCS_TYPE: "gitlab"
    KUBECHECKS_ARGOCD_API_SERVER_ADDR: "10.110.228.250"
    KUBECHECKS_ARGOCD_API_INSECURE: "true"
    KUBECHECKS_NAMESPACE: "kubechecks"
    KUBECHECKS_ARGOCD_REPOSITORY_INSECURE: "true"
```

It seems the app is found during Kubechecks startup

```
8:00PM DBG Debug level logging enabled.
8:00PM TRC Trace level logging enabled.
8:00PM INF Initialized logger.
8:00PM INF setting logrus log level log_level=error
8:00PM INF Starting KubeChecks git-commit=484c48d git-tag=v2.4.0
8:00PM INF parsing configuration
8:00PM INF Server Configuration:
8:00PM INF Webhook URL Base:
8:00PM INF Webhook URL Prefix:
8:00PM INF VCS Type: gitlab
8:00PM INF ArgoCD Namespace: argocd
8:00PM DBG Token Length - 20
8:00PM INF ArgoCD client configuration auth-token=236 grpc-web-root-path= insecure=true server-addr=10.110.228.250
8:00PM DBG add app appName=bitnami-nginx cluster-name= cluster-server=https://kubernetes.default.svc source=
```

but the merge request event always ends in something like

```
7:34PM INF repo has been cloned
7:34PM DBG building command args=["symbolic-ref","refs/remotes/origin/HEAD","--short"]
7:34PM DBG building command args=["merge","origin/aaaa"]
7:34PM DBG building command args=["diff","--name-only","origin/main"]
7:34PM DBG Changed files: bitnami-nginx.yaml event_id=3 repo=test-kubechecks
7:34PM DBG using the argocd matcher
7:34PM DBG looking for https://...@gitlab.example.com/.../test-kubechecks repos
7:34PM DBG mapped apps app_dirs=0 app_files=0 apps=0
7:34PM DBG creating fs for /tmp/kubechecks-repo-709709395
7:34PM DBG following kustomize apps
7:34PM DBG mapped apps app_dirs=0 app_files=0 apps=0
7:34PM DBG looking for https://...@gitlab.example.com/.../test-kubechecks repos
7:34PM DBG found 0 appSets
7:34PM DBG checking 1 changes
7:34PM DBG change: bitnami-nginx.yaml
7:34PM DBG matched 1 files into 0 apps
7:34PM DBG checking 1 changes type=applicationsets
7:34PM DBG change: bitnami-nginx.yaml
7:34PM DBG matched 1 files into 0 appset source=appset_directory
7:34PM DBG Affected apps: [] event_id=3 repo=test-kubechecks
7:34PM DBG Affected appSets: [] event_id=3 repo=test-kubechecks
7:34PM DBG Tidying outdated comments
7:34PM DBG hiding outdated comments
7:34PM INF No affected apps or appsets, skipping event_id=3 repo=test-kubechecks
```

I tried various naming, subfolders etc.

Any idea what am I doing wrong? Or is this just not supported? In all of the examples I saw that the helm chart was placed in the same repository as the ArgoCD Application manifest, but I did not find any clear instructions whether a naming convention needs to be followed.
