### ISSUE TITLE
Kubecheck Report -> No changes

### ISSUE THREAD

**Issue by teo9806** [zapier/kubechecks#420]
Hey,

I need assistance on why I see "no changes" when I open a PR every time. I installed the latest helm chart version (0.5.5). Below you can find some example logs. Please advice!

![Image](https://github.com/user-attachments/assets/c050e079-e70c-4bd7-b770-e0a365369824)

```
 # Labels to apply to all resources created by this Helm chart
argocd:
  namespace: argocd

commonLabels: {}

configMap:
  create: true
  env: 
    KUBECHECKS_ADDITIONAL_APPS_NAMESPACES: "*"
    GRPC_ENFORCE_ALPN_ENABLED: false
    KUBECHECKS_ARGOCD_API_INSECURE: "true"
    KUBECHECKS_ARGOCD_API_PLAINTEXT: 'false'
    KUBECHECKS_ARGOCD_API_PATH_PREFIX: /
    KUBECHECKS_ARGOCD_REPOSITORY_ENDPOINT: "argocd-repo-server.argocd:8081"
    KUBECHECKS_ARGOCD_API_NAMESPACE: "argocd"
    KUBECHECKS_KUBERNETES_TYPE: "local"
    KUBECHECKS_KUBERNETES_CLUSTERID: "staging"
    KUBECHECKS_FALLBACK_K8S_VERSION: "1.27.0"
    KUBECHECKS_LOG_LEVEL: "trace"
    KUBECHECKS_PERSIST_LOG_LEVEL: "true"
    KUBECHECKS_SHOW_DEBUG_INFO: "true"
    KUBECHECKS_WEBHOOK_URL_BASE: "http://kubechecks-poc.yotpodev.com:8080"
    KUBECHECKS_ARGOCD_API_SERVER_ADDR: "argocd.k8s.yotpodev.com"
    KUBECHECKS_OTEL_COLLECTOR_PORT: "4317"
    KUBECHECKS_OTEL_ENABLED: "false"
    KUBECHECKS_VCS_TYPE: "github"
    KUBECHECKS_ENABLE_KUBECONFORM: "true"
    KUBECHECKS_ENABLE_CONFTEST: "true"
    KUBECHECKS_MONITOR_ALL_APPLICATIONS: "true"
    KUBECHECKS_ENSURE_WEBHOOKS: "true"
    KUBECHECKS_TIDY_OUTDATED_COMMENTS_MODE: "delete"
    KUBECHECKS_ENABLE_HOOKS_RENDERER: "true"

deployment:
  annotations: {}

  podAnnotations: {}

  args: []

  # Default values for kubechecks.
  resources:
    limits:
      memory: 512Mi
    requests:
      memory: 256Mi
      cpu: 200m

  revisionHistoryLimit: 10
  replicaCount: 1

  image:
    pullPolicy: Always
    name: "ghcr.io/zapier/kubechecks"
    tag: "latest"

  imagePullSecrets: []

  nodeSelector: 
    product-line: infra
    node.kubernetes.io/lifecycle: spot

  tolerations: 
  - key: "scaler"
    operator: "Equal"
    value: "castai"
    effect: "NoSchedule"
  - key: "product-line"
    operator: "Equal"
    value: "infra"
    effect: "NoSchedule"

  affinity: {}

  podSecurityContext: {}

  securityContext: {}

  env: []
  envFrom: []

  startupProbe:
    failureThreshold: 30
    periodSeconds: 10

  livenessProbe:
    failureThreshold: 30
    initialDelaySeconds: 5
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 5

  readinessProbe:
    failureThreshold: 30
    initialDelaySeconds: 5
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 5

  volumes: []
  volumeMounts: []

secrets:
  create: true
  name: '{{ include "kubechecks.fullname" . }}'
  env:
    KUBECHECKS_VCS_TOKEN: "+++++++++++++"
    KUBECHECKS_ARGOCD_API_TOKEN: "++++++++++"

serviceAccount:
  # Specifies whether a service account should be created or used
  create: true
  enabled: true
  name: '{{ include "kubechecks.fullname" . }}'
  annotations: {}

service:
  create: true
  type: LoadBalancer
  port: 8080
  name: http

ingress:
  create: false
  className: ""
  hosts:
    kubechecks.local:
      paths:
        - path: "/hooks"
          pathType: Prefix

autoscaling:
  create: false
```

Example logs:
```
3:20PM INF repo has been cloned
3:20PM DBG building command args=["symbolic-ref","refs/remotes/origin/HEAD","--short"]
3:20PM DBG building command args=["merge","origin/teo9806-patch-1"]
3:20PM DBG building command args=["diff","--name-only","origin/master"]
3:20PM DBG Changed files: staging/helm-values-files/devops/certificates-exporter/x509-certificates-exporter.yaml event_id=3268 repo=kubernetes-configurations
3:20PM DBG using the argocd matcher
3:20PM DBG looking for https://opsyotpo@github.com/YotpoLtd/kubernetes-configurations repos
3:20PM DBG mapped apps app_dirs=2 app_files=0 apps=99
3:20PM DBG creating fs for /tmp/kubechecks-repo-1909031963
3:20PM DBG following kustomize apps
3:20PM INF processing directory "."
3:20PM INF processing directory "."
3:20PM INF processing directory "."
3:20PM INF processing directory "."
3:20PM INF processing directory "."
3:20PM INF processing directory "."
3:20PM INF processing directory "."
3:20PM INF processing directory "."
3:20PM INF processing directory "."
3:20PM INF processing directory "."
3:20PM INF processing directory "staging/standAlone-yamls"
3:20PM DBG mapped apps app_dirs=2 app_files=0 apps=0
3:20PM DBG looking for https://opsyotpo@github.com/YotpoLtd/kubernetes-configurations repos
3:20PM DBG found 1 appSets
3:20PM DBG checking 1 changes
3:20PM DBG change: staging/helm-values-files/devops/certificates-exporter/x509-certificates-exporter.yaml
3:20PM DBG matched 1 files into 0 apps
3:20PM DBG checking 1 changes type=applicationsets
3:20PM DBG change: staging/helm-values-files/devops/certificates-exporter/x509-certificates-exporter.yaml
3:20PM DBG matched 1 files into 0 appset source=appset_directory
3:20PM DBG Affected apps: [] event_id=3268 repo=kubernetes-configurations
3:20PM DBG Affected appSets: [] event_id=3268 repo=kubernetes-configurations
3:20PM DBG Pruning messages from PR 3268 in repo YotpoLtd/kubernetes-configurations
3:20PM INF No affected apps or appsets, skipping event_id=3268 repo=kubernetes-configurations
3:20PM DBG Posting message to PR 3268 in repo YotpoLtd/kubernetes-configurations
3:20PM DBG Received hook request
3:20PM INF ignoring Github issue comment due to invalid action action=deleted
3:20PM DBG Ignoring event, not a supported request
3:20PM DBG wiping path path=/tmp/kubechecks-repo-1909031963
3:20PM DBG Received hook request
3:20PM INF ignoring Github issue comment event due to non matching string action=created
3:20PM DBG Ignoring event, not a supported request
```
