### ISSUE TITLE
ArgoCD authentication

### ISSUE THREAD

**Issue by bauerjs1** [zapier/kubechecks#53]
Hello again,

I am not yet sure, how to get a long-lived API token from ArgoCD. I managed fetching a token [this way](https://argo-cd.readthedocs.io/en/stable/developer-guide/api-docs/) but it seems like it is only valid for 24h. Wouldn't it make more sense to provide Kubechecks a dedicated user account so it can fetch its own API tokens?

**Comment by morey-tech** [comment]
The way you reference is for generating a (short-lived) session token. It's probably preferred to [create a dedicated local user in Argo CD](https://argo-cd.readthedocs.io/en/stable/operator-manual/user-management/#create-new-user) and generate an API token for it (which will be long-lived) for uses in automation tool likes kubechecks.

**For example:**
Create a user named `kubechecks` in `argocd-cm`.
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  accounts.kubechecks: apiKey
  accounts.kubechecks.enabled: "true"
```
Then generate a token for it (log into the CLI with the admin user):
```
argocd account generate-token --account kubechecks
```

This may be a good example to include in the docs.
