### ISSUE TITLE
Diffing applications doesn't work when generated from an app-of-app-sets

### ISSUE THREAD

**Issue by audrey-mux** [zapier/kubechecks#78]
We're starting to use Helm directly within ArgoCD more often vs rendering them via a CMP.  Are Helm rendering diffs supported? 

For example 

```
argocd app diff <cluster>-grafana-agent-operator --revision fix-name

===== /ConfigMap <cluster>-monitoring/grafana-agent-traces ======
13c13
<                 value: <cluster>1
---
>                 value: <cluster>2
```

Produces `no changes` in the kubechecks output

I tried with both the `argocd matcher` and the `best effort matcher`

**Comment by audrey-mux** [comment]
Yep, heres the one in question.  It was newly installed in this cluster and i screwed up some values in the cluster-specific file we pass.  

No sync window for this one, the root app is set for auto-sync

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: grafana-agent-operator
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: <cluster>
            values:
              environment: staging
  template:
    metadata:
      name: "{{name}}-grafana-agent-operator"
      labels:
      annotations:
        argocd.argoproj.io/manifest-generate-paths: .;/tools/argo/cd/apps/thirdparty/grafana-agent
    spec:
      syncPolicy:
        syncOptions:
          - RespectIgnoreDifferences=true
      destination:
        name: "{{name}}"
        namespace: "{{name}}-monitoring"
      project: "{{name}}"
      source:
        helm:
          releaseName: grafana-agent-operator
          valueFiles:
            - values.yaml
            - "../../{{name}}.yaml"
            - "../../traces-tail-sampling-policies/{{name}}.yaml"
        path: ./tools/argo/cd/apps/thirdparty/grafana-agent/helm/v0.2.15
        repoURL: <path-to-repo>
        targetRevision: main
      ignoreDifferences:
        - group: apps
          kind: Deployment
          name: otel-collector
          namespace: "{{name}}-monitoring"
          jsonPointers:
            - /spec/replicas
        - group: apps
          kind: Deployment
          name: grafana-agent-traces
          namespace: "{{name}}-monitoring"
          jsonPointers:
            - /spec/replicas
 ```
